using Microsoft.EntityFrameworkCore;
using webxemphim.Data;
using webxemphim.Models;

namespace webxemphim.Services
{
    public class SubtitleService
    {
        private readonly ApplicationDbContext _db;
        private readonly ILogger<SubtitleService> _logger;

        public SubtitleService(ApplicationDbContext db, ILogger<SubtitleService> logger)
        {
            _db = db;
            _logger = logger;
        }

        public async Task<List<Subtitle>> GetMovieSubtitlesAsync(int movieId)
        {
            return await _db.Subtitles
                .Where(s => s.MovieId == movieId)
                .OrderBy(s => s.IsDefault ? 0 : 1)
                .ThenBy(s => s.Language)
                .ToListAsync();
        }

        public async Task<Subtitle?> GetSubtitleAsync(int subtitleId)
        {
            return await _db.Subtitles.FindAsync(subtitleId);
        }

        public async Task<Subtitle?> GetDefaultSubtitleAsync(int movieId, string? preferredLanguage = null)
        {
            var query = _db.Subtitles.Where(s => s.MovieId == movieId);
            
            if (!string.IsNullOrEmpty(preferredLanguage))
            {
                var preferred = await query
                    .FirstOrDefaultAsync(s => s.Language == preferredLanguage && s.IsDefault);
                if (preferred != null) return preferred;
            }

            return await query.FirstOrDefaultAsync(s => s.IsDefault) 
                ?? await query.FirstOrDefaultAsync();
        }

        public async Task<Subtitle> AddSubtitleAsync(int movieId, string language, string languageName, string fileUrl, string? filePath = null, bool isDefault = false, bool isAutoGenerated = false, string? uploadedBy = null)
        {
            // Nếu set làm default, bỏ default của các subtitle khác
            if (isDefault)
            {
                var existingDefaults = await _db.Subtitles
                    .Where(s => s.MovieId == movieId && s.IsDefault)
                    .ToListAsync();
                foreach (var sub in existingDefaults)
                {
                    sub.IsDefault = false;
                }
            }

            var subtitle = new Subtitle
            {
                MovieId = movieId,
                Language = language,
                LanguageName = languageName,
                FileUrl = fileUrl,
                FilePath = filePath,
                IsDefault = isDefault,
                IsAutoGenerated = isAutoGenerated,
                UploadedBy = uploadedBy,
                CreatedAt = DateTime.UtcNow
            };

            _db.Subtitles.Add(subtitle);
            await _db.SaveChangesAsync();
            return subtitle;
        }

        public async Task<bool> DeleteSubtitleAsync(int subtitleId, string? userId = null)
        {
            var subtitle = await _db.Subtitles.FindAsync(subtitleId);
            if (subtitle == null) return false;

            // Chỉ cho phép xóa nếu là admin hoặc người upload
            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(subtitle.UploadedBy) && subtitle.UploadedBy != userId)
            {
                // Check if user is admin (có thể thêm logic kiểm tra role)
                return false;
            }

            _db.Subtitles.Remove(subtitle);
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<bool> SetDefaultSubtitleAsync(int subtitleId, int movieId)
        {
            var subtitle = await _db.Subtitles.FindAsync(subtitleId);
            if (subtitle == null || subtitle.MovieId != movieId) return false;

            // Bỏ default của các subtitle khác
            var existingDefaults = await _db.Subtitles
                .Where(s => s.MovieId == movieId && s.IsDefault && s.Id != subtitleId)
                .ToListAsync();
            foreach (var sub in existingDefaults)
            {
                sub.IsDefault = false;
            }

            subtitle.IsDefault = true;
            await _db.SaveChangesAsync();
            return true;
        }

        public async Task<UserSubtitleSettings?> GetUserSubtitleSettingsAsync(string userId)
        {
            return await _db.UserSubtitleSettings
                .FirstOrDefaultAsync(s => s.UserId == userId);
        }

        public async Task<UserSubtitleSettings> GetOrCreateUserSubtitleSettingsAsync(string userId)
        {
            var settings = await GetUserSubtitleSettingsAsync(userId);
            if (settings != null) return settings;

            settings = new UserSubtitleSettings
            {
                UserId = userId,
                FontFamily = "Arial",
                FontSize = 16,
                FontColor = "#FFFFFF",
                BackgroundColor = "#000000",
                BackgroundOpacity = 0.7,
                Position = "bottom",
                ShowBackground = true,
                PreferredLanguage = "vi"
            };

            _db.UserSubtitleSettings.Add(settings);
            await _db.SaveChangesAsync();
            return settings;
        }

        public async Task<UserSubtitleSettings> UpdateUserSubtitleSettingsAsync(string userId, string? fontFamily = null, int? fontSize = null, string? fontColor = null, string? backgroundColor = null, double? backgroundOpacity = null, string? position = null, bool? showBackground = null, string? preferredLanguage = null)
        {
            var settings = await GetOrCreateUserSubtitleSettingsAsync(userId);

            if (!string.IsNullOrEmpty(fontFamily)) settings.FontFamily = fontFamily;
            if (fontSize.HasValue) settings.FontSize = fontSize.Value;
            if (!string.IsNullOrEmpty(fontColor)) settings.FontColor = fontColor;
            if (!string.IsNullOrEmpty(backgroundColor)) settings.BackgroundColor = backgroundColor;
            if (backgroundOpacity.HasValue) settings.BackgroundOpacity = backgroundOpacity.Value;
            if (!string.IsNullOrEmpty(position)) settings.Position = position;
            if (showBackground.HasValue) settings.ShowBackground = showBackground.Value;
            if (!string.IsNullOrEmpty(preferredLanguage)) settings.PreferredLanguage = preferredLanguage;

            await _db.SaveChangesAsync();
            return settings;
        }

        public async Task<List<string>> GetAvailableLanguagesAsync(int movieId)
        {
            return await _db.Subtitles
                .Where(s => s.MovieId == movieId)
                .Select(s => s.Language)
                .Distinct()
                .ToListAsync();
        }
    }
}

