using webxemphim.Data;

namespace webxemphim.Models
{
    public class Subtitle
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public string Language { get; set; } = "vi"; // vi, en, ja, ko, etc.
        public string LanguageName { get; set; } = "Tiếng Việt"; // Tên hiển thị
        public string FileUrl { get; set; } = string.Empty; // URL file .vtt hoặc .srt
        public string? FilePath { get; set; } // Đường dẫn file trên server
        public bool IsDefault { get; set; } = false;
        public bool IsAutoGenerated { get; set; } = false; // Phụ đề tự động
        public string? UploadedBy { get; set; } // User ID nếu user upload
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Navigation properties
        public Movie? Movie { get; set; }
        public ApplicationUser? Uploader { get; set; }
    }

    public class UserSubtitleSettings
    {
        public int Id { get; set; }
        public string UserId { get; set; } = string.Empty;
        public string FontFamily { get; set; } = "Arial";
        public int FontSize { get; set; } = 16;
        public string FontColor { get; set; } = "#FFFFFF";
        public string BackgroundColor { get; set; } = "#000000";
        public double BackgroundOpacity { get; set; } = 0.7;
        public string Position { get; set; } = "bottom"; // bottom, top, middle
        public bool ShowBackground { get; set; } = true;
        public string PreferredLanguage { get; set; } = "vi";

        // Navigation properties
        public ApplicationUser? User { get; set; }
    }
}

